name:                kademlia
version:             0.1.0.0
github:              "mtaylor91/kademlia"
license:             BSD3
author:              "Mike Taylor"
maintainer:          "mike.charles.taylor@gmail.com"
copyright:           "2019 Mike Taylor"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/mtaylor91/kademlia#readme>

dependencies:
- base >= 4.7 && < 5
- async >= 2.2 && < 3
- base >= 4.7 && < 5
- basement >= 0.0.11 && < 0.0.12
- binary >= 0.8.6 && < 0.8.7
- bytestring >= 0.10.8 && < 0.11
- conduit >= 1.3.1 && < 2
- containers >= 0.6 && < 0.7
- cryptonite >= 0.25 && < 0.26
- extra >= 1.6 && < 2
- hex >= 0.1 && < 0.2
- lens >= 4.17 && < 5
- memory >= 0.14 && < 0.15
- network >= 2.8 && < 3
- random >= 1.1 && < 2
- text >= 1.2.3 && < 2
- utf8-string >= 1.0 && < 2
- yesod >=1.6 && <2

library:
  source-dirs: src
  ghc-options:
  - -Wall

executables:
  kademlia:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - kademlia

tests:
  kademlia-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - kademlia
